<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;

class VendorTemplateExport implements FromArray
{
    public function array(): array
    {
        return [
            // Header row
            [
                'Salutation',
                'First Name',
                'Last Name',
                'company Name',
                'display Name',
                'EmailID',
                'Phone',
                'MobilePhone',
                'PAN Number',
                'Payment Terms',
                'Website',
                'Opening Balance',
                'Skype Identity',
                'Department',
                'Designation',
                'Facebook',
                'Twitter',
                'Billing Attention',
                'Billing Address',
                'Billing City',
                'Billing State',
                'Billing Country',
                'Billing Code',
                'Billing Phone',
                'Billing Fax',
                'Shipping Attention',
                'Shipping Address',
                'Shipping City',
                'Shipping State',
                'Shipping Country',
                'Shipping Code',
                'Shipping Phone',
                'Shipping Fax',
                'Vendor Bank Holder Name',
                'Vendor Bank Account Number',
                'Vendor Bank Name',
                'Vendor Bank IFSC Code',
            ],

            // Sample rows
            [
                'Mr.',
                "Aravind's",
                'IVF',
                "Aravind's",
                'Aravinds IVF',
                'aravind@example.com',
                '9876543210',
                '9876543210',
                '33AAAAA0000A1Z5',
                'Due on Receipt',
                '',
                '2000',
                '',
                '',
                '',
                '',
                '',
                '',
                'No.12, Main Street',
                'Chennai',
                'Tamil Nadu',
                'India',
                '600001',
                '9876543210',
                '+1-212-555-1234',
                '',
                'No.12, Main Street',
                'Chennai',
                'Tamil Nadu',
                'India',
                '600001',
                '9876543210',
                '+1-212-555-1234',
                "Aravind's",
                '123456789012',
                'SBI Bank',
                'SBIN0001234',
            ],
            [
                'Mr.',
                "naanee",
                'l',
                "Aravind's",
                'Aravinds IVF',
                'aravind@example.com',
                '9876543210',
                '9876543210',
                '33AAAAA0000A1Z5',
                'Due on Receipt',
                '',
                '2000',
                '',
                '',
                '',
                '',
                '',
                '',
                'No.12, Main Street',
                'Chennai',
                'Tamil Nadu',
                'India',
                '600001',
                '9876543210',
                '+1-212-555-1234',
                '',
                'No.12, Main Street',
                'Chennai',
                'Tamil Nadu',
                'India',
                '600001',
                '9876543210',
                '+1-212-555-1234',
                "Aravind's",
                '123456789012',
                'SBI Bank',
                'SBIN0001234',
            ],
        ];
    }
}
