<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class CheckinModel extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'tbl_checkin_report';

    protected $fillable = [
        'blue_book_pdfs',
        'consent_pdfs',
        'fs_study_pdfs',
        'inj_pdfs',
        'trigger_used_pdfs',
        'antag_doses_pdfs',
        'category',
        'wife_name',
        'loan_management',
        'aft_discount',
        'wife_mrd_number',
        'husband_name',
        'husband_mrd_number',
        'procedure_name',
        'cycle_no',
        'package_type',
        'package_amount',
        'fs_study_injections_used',
        'antag_doses_till_trigger',
        'trigger_used',
        'actual_discount',
        'expected_discount',
        'approved_discount',
        'paid_status',
        'consent_type_pdf',
        'blue_book_pdf',
        'cc_handled',
        'consultant_name',
        'crm_incharge',
        'checkinkey',
        'zone_id',
        'location_id',
        'branch_id',
        'doctor_name',
        'cc_employment_id',
        'patient_age',
        'treat_amt',
        'treatment_category',
        'stage_of_treatment',
        'cc_name',
        'cc_audit_name',
        'ip_phar_due',
        'next_appointment_date',
        'ef_fet_ilnj',
        'od_fet_legal',
        'ed_fet_legal',
        'patient_area',
        'speciality',
        'mobile',
        'age',
        'phid',
        'title',
        'lname',
        'dob',
        'gender',
        'ptsource',
        'familyid',
        'isdcode',
        'address2',
        'relationship',
        'street',
        'area',
        'landmark',
        'city',
        'state',
        'zip',
        'country',
        'created_att',
        'updated_att',
        'co_user_dt',
        'co_user_name',
        'co_user',
        'cc_audit_id',
        'credit_provider',
        'purpose',
        'natureofvisit',
        'unregistered_dr',
        'referredbykey',
        'referred_by',
        'token',
        'createdby',
        'createdby_name',
        'checkin_date',
        'start',
        'bookeddr',
        'bookeddr_name',
        'consultingdr',
        'consultingdr_name',
        'entitykey',
        'apptkey',
        'entitylocation',
        'branch',
        'opno',
        'hadmlc',
        'hadfood',
        'dr_dept',
        'type',
        'created_at',
        'updated_at'
    ];

}
